author: vioCode
description: Vital commands for every server owner.
main: co.viocode.nexus.Nexus
name: Nexus
url: http://viocode.co/
version: 0.4.0
commands:
  ban:
    usage: /<command> (player) (reason)
  broadcast:
    usage: /<command> (message)
  heal:
    usage: /<command> (player)
  inv:
    usage: /<command> [clear|edit] (player)
  kick:
    usage: /<command> (player) (reason)
  kill:
    usage: /<command> (player)
  level:
    usage: /<command> (player) (level)
  mode:
    usage: /<command> (player)
  mute:
    usage: /<command> (player)
  online:
    usage: /<command>
  r:
    usage: /<command> (message)
  spawn:
    usage: /<command> [set]
  tp:
    usage: /<command> [toggle] (player) (player)
  tpc:
    usage: /<command> (x) (y) (z)
  tpr:
    usage: /<command> [accept|deny|cancel] (player)
  time:
    usage: /<command> [dawn|day|dusk|night|lock]
  unban:
    usage: /<command> (player)
  unmute:
    usage: /<command> (player)
  wp:
    usage: /<command> [set|del|list] (waypoint)
  weather:
    usage: /<command> [clear|rain|storm|lock]
  w:
    usage: /<command> (player) (message)