author: Stephen Monroe (VioVioCity)
main: co.viocode.legacy.Legacy
name: Legacy
version: 1.2.4
commands:
  legacy:
    description: Displays server play time.
    usage: /<command> (player)
permissions:
  legacy.check:
    description: Allows use of /legacy.
    default: op
  legacy.others:
    description: Allows use of /legacy (player)
    default: op
  legacy.top:
    description: Allows use of /legacy (leaderboard)
    default: op