author: Stephen Monroe (VioVioCity)
main: me.vioviocity.legacy.Legacy
name: Legacy
version: 0.1.0
commands:
  legacy:
    description: Displays server play time.
    usage: /<command> (player)
permissions:
  legacy.check:
    description: Allows use of /legacy.
    default: op
  legacy.check.others:
    description: Allows use of /legacy (player)
    default: op