author: vioCode
description: Vital commands for every server owner.
main: co.viocode.nexus.Nexus
name: Nexus
url: http://viocode.co/
version: 0.4.0
commands:
  broadcast:
    usage: /<command> (message)
  heal:
    usage: /<command> (player)
  kill:
    usage: /<command> (player)
  level:
    usage: /<command> (player) (level)
  mode:
    usage: /<command> (player)
  online:
    usage: /<command>
  time:
    usage: /<command> [dawn|day|dusk|night|lock]
  weather:
    usage: /<command> [clear|rain|storm|lock]