author: vioCode
main: co.viocode.legacy.Legacy
name: Legacy
url: http://viocode.co/
version: 1.3.0
commands:
  legacy:
    description: Displays server play time.
    usage: /<command> (player)
permissions:
  legacy.check:
    description: Allows use of /legacy.
    default: op
  legacy.others:
    description: Allows use of /legacy (player)
    default: op
  legacy.top:
    description: Allows use of /legacy (leaderboard)
    default: op